### ISSUE TITLE
Downloading images from artifactory.nordix.org is extremely slow

### ISSUE THREAD

**Issue by mboutet** [metal3-io/metal3-dev-env#1148]
Is this expected/a known issue that downloading images from https://artifactory.nordix.org is extremely slow? I consistently observe slow download speeds from nordix when running `make` in the dev env.

This command has been running for almost 1h30m:

```bash
wget --no-verbose --no-check-certificate https://artifactory.nordix.org/artifactory/metal3/images/k8s_v1.26.0/CENTOS_9_NODE_IMAGE_K8S_v1.26.0.qcow2
```

I'm located in Montreal (Canada) and a speed test shows 118.9 Mbps download.

Downloading the image via my browser also shows speeds of 100kbps-300kbps.

Thank you

**Comment by furkatgofurov7** [comment]
@mboutet Hi, thanks for reaching out. We have seen the similar issues in the past but did not really bother about it since Metal3 community does not maintain the nordix artifactory. However, we have reached out to artifactory admins to know more about issue and possible solution to it. I will update here when we have more information on this.  

/triage accepted

**Comment by tuminoid** [comment]
Same here, I was getting 2.5MB/s max yesterday, and today I average 10x and the download completed in 97s. Great improvement!

**Comment by mboutet** [comment]
Much better now! Thank you
