### ISSUE TITLE
Create and manage additional Clusters on metal3-dev-env

### ISSUE THREAD

**Issue by sb1975** [metal3-io/metal3-dev-env#33]
I cannot see the clusters pls
$ kubectl --kubeconfig .kube/config get machines --all-namespaces
NAMESPACE   NAME     PROVIDERID   PHASE
metal3      centos
[user@centos7 ~]$ kubectl --kubeconfig .kube/config get clusters --all-namespaces
No resources found.
Steps to create and manage additional cluster will be helpful.

**Comment by russellb** [comment]
cluster-api-provider-baremetal does not yet support creating `Cluster` resources.  With `v1alpha1` of the cluster-api, Cluster support is coupled with each provider.  Ideally, each provider only supports infrastructure provisioning, and control plane provisioning is handled by another layer.  We've only implemented the infrastructure provisioning part.

It seems that a goal of the next version of cluster-api, `v1alpha2`, is to provide better separation of concerns.  Instead of investing in Cluster support of `v1alpha1`, I'd prefer effort be put into helping the cluster-api project on its next version.  Until then, we're just supporting `Machine` resources.

There's some more discussion here: https://github.com/metal3-io/cluster-api-provider-baremetal/issues/67

Hope that helps.

**Comment by sb1975** [comment]
Closing since this is already open with this reference - https://github.com/metal3-io/cluster-api-provider-baremetal/issues/67
