### ISSUE TITLE
Provision controlplane and worker fails in metal3-dev-env

### ISSUE THREAD

**Issue by ankit-kumar5** [metal3-io/metal3-dev-env#432]
I installed metal3-dev-env by following this https://metal3.io/try-it.html#12-metal3-dev-env-setup. I have attached the config_centos.sh file which i used. 
[config_centos.txt](https://github.com/metal3-io/metal3-dev-env/files/5083567/config_centos.txt)

I want to provision real hardware. I have added 2 BM nodes which are in ready state. When i am triggering the **metal3-dev-env/vm-setup/scripts/v1alphaX/provision_controlplane.sh** , its is taking default values for **IMAGE_URL** and **IMAGE_CHECKSUM** (For Ex: IMAGE_URL=http://172.22.0.1/images/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64-raw.img) and other variables. I want to make changes to variables provided in **metal3-dev-env/vm-setup/roles/v1aX_integration_test/files/manifests/clusterctl_env_centos.rc** or  **metal3-dev-env/vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc** and use those for provisioning cluster, controlplane and worker. Where should i make the changes to take effect?

Thanks in advance.

**Comment by fmuyassarov** [comment]
Sorry if the documentation wasn't really clear. We are working now on improving our documentation.

Those vars are declared and exported in [lib/images.sh](https://github.com/metal3-io/metal3-dev-env/blob/master/lib/images.sh).
If you want to have your custom value for `IMAGE_URL` and `IMAGE_CHECKSUM`, then please export them with desired value before running `make`.

e.g.
```
export IMAGE_URL=URL_TO_IMAGE
export IMAGE_CHECKSUM=URL_TO_IMAGE_MD5SUM
```

**Comment by fmuyassarov** [comment]
**Correction to the above comment:**

Exporting will not work because If you just export, the value will be overwritten anyways.
You will need to add your desired value in lib/images.sh in [/vm-setup/roles/v1aX_integration_test/vars/main.yml](https://github.com/metal3-io/metal3-dev-env/blob/cd27bf393407fb8a371c7d23354fd52d78107113/vm-setup/roles/v1aX_integration_test/vars/main.yml), [L60](https://github.com/metal3-io/metal3-dev-env/blob/cd27bf393407fb8a371c7d23354fd52d78107113/vm-setup/roles/v1aX_integration_test/vars/main.yml#L60) and [L61](https://github.com/metal3-io/metal3-dev-env/blob/cd27bf393407fb8a371c7d23354fd52d78107113/vm-setup/roles/v1aX_integration_test/vars/main.yml#L61)

**Comment by ankit-kumar5** [comment]
> Sorry if the documentation wasn't really clear. We are working now on improving our documentation.
> 
> Those vars are declared and exported in [lib/images.sh](https://github.com/metal3-io/metal3-dev-env/blob/master/lib/images.sh).
> If you want to have your custom value for `IMAGE_URL` and `IMAGE_CHECKSUM`, then please export them with desired value before running `make`.
> 
> e.g.
> 
> ```
> export IMAGE_URL=URL_TO_IMAGE
> export IMAGE_CHECKSUM=URL_TO_IMAGE_MD5SUM
> ```

Yeah.. i tried but it was getting overwritten.

**Comment by ankit-kumar5** [comment]
> **Correction to the above comment:**
> 
> Exporting will not work because If you just export, the value will be overwritten anyways.
> You will need to add your desired value in lib/images.sh in [/vm-setup/roles/v1aX_integration_test/vars/main.yml](https://github.com/metal3-io/metal3-dev-env/blob/cd27bf393407fb8a371c7d23354fd52d78107113/vm-setup/roles/v1aX_integration_test/vars/main.yml), [L60](https://github.com/metal3-io/metal3-dev-env/blob/cd27bf393407fb8a371c7d23354fd52d78107113/vm-setup/roles/v1aX_integration_test/vars/main.yml#L60) and [L61](https://github.com/metal3-io/metal3-dev-env/blob/cd27bf393407fb8a371c7d23354fd52d78107113/vm-setup/roles/v1aX_integration_test/vars/main.yml#L61)

I am bit confused.. I have to add variables in lib/images.sh. /vm-setup/roles/v1aX_integration_test/vars/main.yml, L60 and L61 this is just reference for that. Am i correct?

**Comment by ankit-kumar5** [comment]
Hi, 
Changing the variables in **/vm-setup/roles/v1aX_integration_test/vars/main.yml, L60 and L61** worked. Thanks for helping.

I have one more doubt i want to make some modification for this **CTLPLANE_KUBEADM_EXTRA_CONFIG** based on my environment. Adding that **/vm-setup/roles/v1aX_integration_test/vars/main.yml, L60 and L61** will work?

**Comment by fmuyassarov** [comment]
> Hi,
> Changing the variables in **/vm-setup/roles/v1aX_integration_test/vars/main.yml, L60 and L61** worked. Thanks for helping.
> 
> I have one more doubt i want to make some modification for this **CTLPLANE_KUBEADM_EXTRA_CONFIG** based on my environment. Adding that variable with updated info in **/vm-setup/roles/v1aX_integration_test/vars/main.yml** will work?


We don't declare `CTLPLANE_KUBEADM_EXTRA_CONFIG` in /vars/main.yaml but instead inside the templates.
If you want to modify `CTLPLANE_KUBEADM_EXTRA_CONFIG` value you would rather do it within the templates in [vm-setup/roles/v1aX_integration_test/templates/](https://github.com/metal3-io/metal3-dev-env/tree/b156fcafcf47b982c4cc5ad8c08d55d60d592b6e/vm-setup/roles/v1aX_integration_test/templates). 
If you want CentOS for your target nodes then you need to modify `CTLPLANE_KUBEADM_EXTRA_CONFIG` var value in [clusterctl_env_template_centos.rc](https://github.com/metal3-io/metal3-dev-env/blob/b156fcafcf47b982c4cc5ad8c08d55d60d592b6e/vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_centos.rc#L25), otherwise [clusterctl_env_template_ubuntu.rc](https://github.com/metal3-io/metal3-dev-env/blob/b156fcafcf47b982c4cc5ad8c08d55d60d592b6e/vm-setup/roles/v1aX_integration_test/templates/clusterctl_env_template_ubuntu.rc#L25) for Ubuntu nodes.

**Comment by ankit-kumar5** [comment]
Its taking the changes. Thanks..
