### ISSUE TITLE
Qemu logs are absent in Centos CI runs

### ISSUE THREAD

**Issue by kashifest** [metal3-io/metal3-dev-env#438]
Qemu logs (cloud init logs for target nodes) are empty in centos CI runs. 

Here is a reference: 

https://jenkins.nordix.org/view/Airship/job/airship_master_v1a4_integration_test_centos/215/artifact/logs-jenkins-airship_master_v1a4_integration_test_centos-215.tgz

A quick investigation reveals the following error: 

```
Fetching logs
Warning: Permanently added '10.100.10.189' (ECDSA) to the list of known hosts.
cp: cannot stat '/var/log/libvirt/qemu/*': No such file or directory
logs-jenkins-airship_master_v1a4_integration_test_centos-215/k
```

**Comment by Jaakko-Os** [comment]
The 'libvirt' and 'qemu' directories are located on the jenkins master VM. The reported issue is seen because the directory is being accessed on the jenkins slave whereit doesn't exist.

airshipci@ci-test-vm-20200821041037-ehbw:~$ ls -l /var/log/libvirt/qemu/
total 1024
-rw------- 1 root root 323680 Aug 21 04:44 node_0-serial0.log
-rw------- 1 root root  12712 Aug 21 04:41 node_0.log
-rw------- 1 root root 302427 Aug 21 04:52 node_1-serial0.log
-rw------- 1 root root  12754 Aug 21 04:50 node_1.log
-rw------- 1 root root 160982 Aug 21 04:34 node_2-serial0.log
-rw------- 1 root root  12730 Aug 21 05:16 node_2.log
-rw------- 1 root root 182982 Aug 21 04:35 node_3-serial0.log
-rw------- 1 root root  12766 Aug 21 05:14 node_3.log

metal3@test1-pwgvh:~$ ls -l /var/log/libvirt
ls: cannot access '/var/log/libvirt': No such file or directory
