### ISSUE TITLE
Unable to setup kind cluster based metal3 setup with user defined IPs due to non-configurable Ironic environment parameters

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/metal3-dev-env#443]
When Ubuntu OS, container-runtime selected ( as per #398 ) is Docker & then Ephemeral cluster is Kind based.
User makes changes as per his required IPs & other configs in relevant files, and build metal3-dev-env.

However as of now, **this only works with default IPs in lib/network.sh** [using IPs : 172.22.0.1 or 2 for PROVISIONING_IP/CLUSTER_PROVISIONING_IP] & not with user-specified IPs (say with 172.22.0.11 or .22 OR 192.168.121.x)

The reason being while running 03_launch_mgmt_cluster.sh, it clones BMO repo & uses all the Ironic parameters from  baremetal-operator/deploy/ironic_ci.env which has hard-coding of this 172.22.0.x network.

Currently we tested this using custom BMOREPO and BMOBRANCH where our IP specific changes are present in ironic_ci.env.
We were able to on-board Dell PowerEdge servers with these changes where Introspection, Provisioning, De-provisoining were successful. 

In order to make this work with user-specified networks, need to make Ironic parameters configurable in metal3-dev-env, maybe in similar way #333 was done, can be treated as enhancement.

@fmuyassarov please share your thoughts based on our discussion. This makes a good use-case for Metal3.

**Comment by fmuyassarov** [comment]
One way to manipulate [ironic_ci.env](https://github.com/metal3-io/baremetal-operator/blob/master/deploy/ironic_ci.env) with the custom value of `PROVISIONING_IP` would be to overwrite (e.g. with sed) `PROVISIONING_IP` in ironic_ci.env after we clone Baremetal Operator in  [03_launch_mgmt_cluster.sh](https://github.com/metal3-io/metal3-dev-env/blob/5e0009454c8e436b3a688db511f5826b1d9dcef4/03_launch_mgmt_cluster.sh#L21).

**Comment by sumitjadhav1** [comment]
Hi @fmuyassarov couple of more parameters would also need manipulation ? `DHCP_RANGE` & `CACHEURL` as well ?

**Comment by fmuyassarov** [comment]
> Hi @fmuyassarov couple of parameters would also need manipulation ? `DHCP_RANGE` & `CACHEURL` as well ?

Hi,

1. I would say that `CACHE_URL` doesn't need to be changed because it inherits its value from `IRONIC_HOST` var, and `IRONIC_HOST` inherits from `CLUSTER_URL_HOST` and finally `CLUSTER_URL_HOST` inherits from `CLUSTER_PROVISIONING_IP`. So, if you just add your desired IP in [/lib/network.sh](https://github.com/metal3-io/metal3-dev-env/blob/ac1681b57882b3880d8d21ca417c493f7dd654be/lib/network.sh#L56) for `CLUSTER_PROVISIONING_IP` that will have impact on the `CACHE_URL` var as well. 

2.  If you want to stick to the default CIDR (172.22.0.0/24) of the `PROVISIONING_NETWORK`, then you don't need to modify `DHCP_RANGE`. 

     If you don't want to stick to the default CIDR (172.22.0.0/24) of the `PROVISIONING_NETWORK`, then you can modify the CIDR of [PROVISIONING_NETWORK](https://github.com/metal3-io/metal3-dev-env/blob/ac1681b57882b3880d8d21ca417c493f7dd654be/lib/network.sh#L47). However, if you also want to change the range of IP address in a given `PROVISIONING_NETWORK` then [dhcp_range_start](https://github.com/metal3-io/metal3-dev-env/blob/ac1681b57882b3880d8d21ca417c493f7dd654be/lib/network.sh#L78) and [dhcp_range_end](https://github.com/metal3-io/metal3-dev-env/blob/ac1681b57882b3880d8d21ca417c493f7dd654be/lib/network.sh#L79) need to be manipulated with the desired range. 

I agree that we need to make it easier to modify those vars with custom values.

**Comment by maelk** [comment]
Would this be solved with an update of the documentation ? If we make clear which variables to change when changing the network configuration, would that solve your issue ?

**Comment by sumitjadhav1** [comment]
> 
> 
> Would this be solved with an update of the documentation ? If we make clear which variables to change when changing the network configuration, would that solve your issue ?

Yes the documentation update would be helpful. But our observations are : we don't change these variables in ironic_ci.env run-time. So that was the purpose of raising this issue.

**Comment by maelk** [comment]
indeed, if you use the run_local_ironic script then the variables are not set so this actually needs to be modified in that script. All variables must be passed through the environment or defaulted, similarly to what is done in the kustomization here : https://github.com/metal3-io/metal3-dev-env/blob/master/03_launch_mgmt_cluster.sh#L167 . The issue is then in BMO script first, then we need to make sure that all those variables are properly exported in CAPM3.
/help-needed
/good-first-issue

**Comment by fmuyassarov** [comment]
@sumitjadhav1 Hopefully now you should be able to run Metal3-dev-env with custom IP by only exporting/modifying IP related variables Metal3-dev-env, without a need to make changes in BMO side.

**Comment by sumitjadhav1** [comment]
@fmuyassarov : Yes, checked it today only by having two different non-default networks for baremetal & provisioning, able to run metal3-dev-env successfully. Observed another issue logged in #462
